### ISSUE TITLE
Support Intel Compiler 17 Beta

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1447]
For the moment, our test results with Intel Compiler 17 Beta are so bad that we have even stopped trying to support it.

I have filled a bug at Intel, with [this test case]:

> The attached file is not compiled correctly, and the run of it fails. Here is the command lines I have used, and the results:
>
> icpc -V -O1 -o /tmp/test_bug test_bug.cpp && /tmp/test_bug
> Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.0.064 Beta Build 20160517
> Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
> icpc: NOTE: The Beta evaluation period for this product ends on 7-oct-2016 UTC.
> Edison Design Group C/C++ Front End, version 4.10.1 (May 18 2016 01:11:31)
> Copyright 1988-2015 Edison Design Group, Inc.
> GNU ld version 2.25-17.fc23
> (Construction from 0x1a3bc90)
> (Construction from 0x1a3bcb8)
> (Copy-construction from 0x1a3bc90)
> operator++(int)
>  before: 0x1a3bc90 : 1
> (Copy-construction from 0x1a3bc90)
>  operator++()
>  before: 0x1a3bc90 : 1
>  after: 0x1a3bc98 : 2
>  after: 0x1a3bc98 : 2 
>  tmp: 0x1a3bc90 : 1
> test_bug: test_bug.cpp:79: void test_N_step_adaptor(): Assertion `4 == (*begin)' failed.
> 
> If I compile with the flag  -O3 instead of -O1, or if I remove the lines with std::cerr, then the code compiles and run correctly.

[this test case]: https://gist.githubusercontent.com/anonymous/f373ddaadabbd33f6c95a451e0937fe7/raw

**Comment by lrineau** [comment]
The bug seems fixed with Intel Compiler 17 (non-beta, released recently). I will reactivate the compiler in our testsuite platforms...

**Comment by lrineau** [comment]
The bug seems fixed by the latest non-beta version of Intel Compiler 17. The results in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-151.shtml are good.

**Comment by kynan** [comment]
Still getting this build failure with Intel 17 and the CGAL 4.10 release:
```
[ 16%] Building CXX object src/CGAL/CMakeFiles/CGAL.dir/all_files.cpp.o
In file included from [...]/CGAL-4.10/include/CGAL/Kernel/global_functions.h(31),
                 from [...]/CGAL-4.10/include/CGAL/Cartesian/Cartesian_base.h(30),
                 from [...]/CGAL-4.10/include/CGAL/Simple_cartesian.h(28),
                 from [...]/CGAL-4.10/include/CGAL/Bbox_2_Line_2_intersection_impl.h(31),
                 from [...]/CGAL-4.10/src/CGAL/Bbox_2_intersections.cpp(28),
                 from [...]/CGAL-4.10/build/src/CGAL/all_files.cpp(1):
[...]/CGAL-4.10/include/CGAL/Kernel/global_functions_2.h(362): error: invalid argument to attribute "deprecated"
  CGAL_DEPRECATED_MSG("This function is deprecated. CGAL::compare_slope() should be used instead")
  ^

In file included from [...]/CGAL-4.10/include/CGAL/Kernel/global_functions.h(31),
                 from [...]/CGAL-4.10/include/CGAL/Cartesian/Cartesian_base.h(30),
                 from [...]/CGAL-4.10/include/CGAL/Simple_cartesian.h(28),
                 from [...]/CGAL-4.10/include/CGAL/Bbox_2_Line_2_intersection_impl.h(31),
                 from [...]/CGAL-4.10/src/CGAL/Bbox_2_intersections.cpp(28),
                 from [...]/CGAL-4.10/build/src/CGAL/all_files.cpp(1):
[...]/CGAL-4.10/include/CGAL/Kernel/global_functions_2.h(372): error: invalid argument to attribute "deprecated"
  CGAL_DEPRECATED_MSG("This function is deprecated. CGAL::compare_slope() should be used instead")
  ^
```

**Comment by kynan** [comment]
Can you reproduce this @lrineau @mglisse ?

**Comment by lrineau** [comment]
I am now on vacation, for two weeks. I cannot easily access to that compiler from where I am.

**Comment by kynan** [comment]
No worries @lrineau. Anyone else who might be able to confirm?
