### ISSUE TITLE
[Crash] Constrained 2D Delaunay triangulation: assertion violation!

### ISSUE THREAD

**Issue by yobeonline** [CGAL/cgal#2999]
## Issue Details

A crash occurs when inserting a set of constraints that touch each-other (no "full" intersection nor common point)
![config](https://user-images.githubusercontent.com/6747553/38429915-1dbf7592-39c0-11e8-8255-5e8abd7d4d09.png)

On a debug executable, the following message is displayed:

> CGAL error: assertion violation!
> Expression : false
> File       : C:\Sdk\CGAL\4.11.1\include\CGAL/Polyline_constraint_hierarchy_2.h
> Line       : 1013
> Explanation:
> Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html

The defect is very sensitive to there being three constraints, and the order in which the points are given when inserting a particular constraint.

## Source Code
Here is the smallest code snippet I could come up with that reproduces the problem.

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>
#include <CGAL/Triangulation_face_base_2.h>
#include <CGAL/Triangulation_vertex_base_2.h>
#include <CGAL/Delaunay_triangulation_2.h>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Vb2 = CGAL::Triangulation_vertex_base_2<K>;
using Fb2 = CGAL::Constrained_triangulation_face_base_2<K>;
using TDS2 = CGAL::Triangulation_data_structure_2<Vb2,Fb2>;
using Itag2 = CGAL::Exact_predicates_tag;
using CDT2_Base = CGAL::Constrained_Delaunay_triangulation_2<K,TDS2,Itag2>;

using Triangulation = CGAL::Constrained_triangulation_plus_2<CDT2_Base>;
using point = Triangulation::Point;

void main(void)
{
  Triangulation t;

  {
    point const p1(942455, 2306674.6);
    point const p2(942452.3, 2306671.9);
    t.insert_constraint(p1,p2);
  }

  point const p3(942453.8, 2306673.4);
  {
    point const p4(942441.1, 2306667.8);
    t.insert_constraint(p4,p3);
  }

  {
    point const p5(942447.7, 2306686);
    t.insert_constraint(p3,p5);
  }

  return;
}

```

## Environment

* Windows (64 bits)
* Compiler: vs 2013 32 and 64
* Release or debug mode: crash in release, assert in debug
* Specific flags used (if any): none
* CGAL version: 4.11.1 (reproduced with 4.11)
* Boost version: 1.65.1
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by yobeonline** [comment]
So close to #3000…

**Comment by lrineau** [comment]
p1, p2, and p3 are not collinear.

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>
#include <CGAL/Triangulation_face_base_2.h>
#include <CGAL/Triangulation_vertex_base_2.h>
#include <CGAL/Delaunay_triangulation_2.h>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Vb2 = CGAL::Triangulation_vertex_base_2<K>;
using Fb2 = CGAL::Constrained_triangulation_face_base_2<K>;
using TDS2 = CGAL::Triangulation_data_structure_2<Vb2,Fb2>;
using Itag2 = CGAL::Exact_predicates_tag;
using CDT2_Base = CGAL::Constrained_Delaunay_triangulation_2<K,TDS2,Itag2>;

using Triangulation = CGAL::Constrained_triangulation_plus_2<CDT2_Base>;
using point = Triangulation::Point;

int main(void)
{
  Triangulation t;

  point const p1(942455, 2306674.6);
  point const p2(942452.3, 2306671.9);
  t.insert_constraint(p1,p2);

  point const p3(942453.8, 2306673.4);
  point const p4(942441.1, 2306667.8);
  t.insert_constraint(p4,p3);

  point const p5(942447.7, 2306686);
  assert(orientation(p1, p3, p2) == CGAL::COLLINEAR);
  t.insert_constraint(p3,p5);
}
```

Anyway, I can reproduce the bug with `master`.

**Comment by lrineau** [comment]
I assign the bug to Andreas Fabri, author of `Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h`, where the assertion is triggered.

It seems `]p3, p4]` and `]p3, p5]` do intersect `[p1, p2]`, but the intersection is tiny. Maybe the bug is because of that.

If we remove `CGAL::Constrained_triangulation_plus_2` from the equation, the crash disappear (but probably the produced triangulation has tiny elements.

**Comment by lrineau** [comment]
Ping @afabri. That seems a real bug of the CDT_2 with hierarchy.

**Comment by lrineau** [comment]
@afabri 

The submitted code also works well with CGAL-4.5.1, just before the new `Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h` was introduced.

**Comment by lrineau** [comment]
A fix for this bug has been merged in the release branches targeting CGAL-4.11.2 and CGAL-4.12.1, as well as in `master` (targeting CGAL-4.13-beta1). It is the PR #3098.

I hope the fix is also sufficient for your larger data set. Let us know if you get similar runtime errors with different sets of segments.

**Comment by yobeonline** [comment]
Good news !

I am unable to test this new release right away. I will let you know asap.

Thank you for the work on this issue.

**Comment by yobeonline** [comment]
I have some time to test the fix on my dataset. Where can I find either source-version 4.11.2 or 4.12.1 for download?

PS I have found two similar issues on release 4.11.1, but I will test the fix on them before I issue a bug report.

**Comment by MaelRL** [comment]
Neither of these versions have been officially released just yet. You can use their respective development branch to test the fix:
- 4.11.2: https://github.com/CGAL/cgal/tree/releases/CGAL-4.11-branch
- 4.12.1: https://github.com/CGAL/cgal/tree/releases/CGAL-4.12-branch
- 4.13: https://github.com/CGAL/cgal/tree/master

You can download the source for each branch with the "clone or download" button, e.g. https://github.com/CGAL/cgal/archive/releases/CGAL-4.12-branch.zip for the 4.12 branch.

**Comment by yobeonline** [comment]
Thanks,

Any idea when they will be officially released ?

**Comment by sloriot** [comment]
FYI 4.11.2 has been just released

**Comment by yobeonline** [comment]
Hmm. I am sorry, but the release 4.11.2 that has just been released doesn't solve the bug I reported and the code I posted still fails with the same message.

I built the 4.11.2 release with the same script that I used for 4.11.1 and the assert violation message confirms that I am building with 4.11.2 (the path to Polyline_constraint_hierarchy_2.h confirms). I clean-rebuilt the file.

**Comment by lrineau** [comment]
I confirm that the original bug is not fixed. It is only fixed if the `triangulation_plus_2` is not used:
```c++
using Triangulation = CDT2_Base;
```

**Comment by lrineau** [comment]
There was an issue with our fix. We merged another fix: PR #3232. It will be in CGAL-4.12.1 and CGAL-4.11.3.

**Comment by hanilan** [comment]
Hello,
I still have the issue with CGAL 4.13 and a lot a subconstraint intersections, here my settings : 
![image](https://user-images.githubusercontent.com/52419411/68950798-2a699f80-07bd-11ea-9230-83427dd3a160.png).
Let' me know if I need to upgrade, I didn't see another thread about that. I'll try to send you a data set to reproduce it.

Thanks

**Comment by lrineau** [comment]
@hanilan  Please send us a reproducible and self-contained .cpp file (including the data), so that we can work on the issue.

**Comment by hanilan** [comment]
Thank you for your answer, I'll try to isolate the constraints that make the crash to simplify the debug for you. Thanks

**Comment by hanilan** [comment]
Hello, 
you can find below a sample that makes the crash.

#include <CGAL/Constrained_triangulation_plus_2.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Projection_traits_xy_3.h>
#include <CGAL/Triangulation_face_base_with_info_2.h>
#include <CGAL/Triangulation_vertex_base_with_id_2.h>

	typedef CGAL::Epick Kernel;
    typedef Kernel::FT FieldNumberType;
    typedef Kernel::Point_2 Point2;
    typedef Kernel::Point_3 Point3;
	typedef CGAL::Projection_traits_xy_3<Kernel> TriangulationTraits;
    typedef CGAL::Triangulation_vertex_base_with_id_2<TriangulationTraits> VertexBaseWithId;
    typedef CGAL::Triangulation_vertex_base_2<TriangulationTraits, VertexBaseWithId> VertexBase;
    typedef CGAL::Triangulation_face_base_with_info_2<FaceInfo2, Kernel> FaceBaseWithInfo;
    typedef CGAL::Constrained_triangulation_face_base_2<TriangulationTraits, FaceBaseWithInfo> FaceBase;
    typedef CGAL::Triangulation_data_structure_2<VertexBase, FaceBase> TriangulationData;
    typedef CGAL::Constrained_Delaunay_triangulation_2<TriangulationTraits, TriangulationData, CGAL::Exact_predicates_tag> ConstrainedTriangulation;
    typedef CGAL::Constrained_triangulation_plus_2<ConstrainedTriangulation> CDT;
	
	void TriangulateCrash()
    {
        CDT cdt;
        const Point3 A(539.5294108288881, 332.45151278002265, 109.660400390625);
        const Point3 B(538.779296875, 329.10546875, 109.707275390625);
        const Point3 C(539.74609375, 332.431640625, 109.660400390625);
        const Point3 D(539.68266371486789, 333.13513011783971, 109.649658203125);
        const Point3 E(539.52898179930912, 332.45155212665065, 109.660400390625);
        cdt.insert_constraint(A, B);
        cdt.insert_constraint(C, A);
        cdt.insert_constraint(D, B);
        cdt.insert_constraint(C, E);
    }

**Comment by lrineau** [comment]
I have created the issue #4405 to track that new bug.

**Comment by afabri** [comment]
> 
> 
> I have created the issue #4405 to track that new bug.

I have create the PR #4406 which should fix your bug.
