### ISSUE TITLE
Failing to compile repair_polygon_soup_example.cpp

### ISSUE THREAD

**Issue by domparise** [CGAL/cgal#3881]
New user trying to use CGAL for a project. Specifically trying compile and use mesh repair examples.

## Issue Details

Compilation error: Issue compiling calls that are made to "internal_np":
```
In file included from /Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:4:
/usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:893:77: error: no member named 'erase_all_duplicates' in namespace 'CGAL::internal_np'
  const bool erase_all_duplicates = choose_param(get_param(np, internal_np::erase_all_duplicates), false);
/usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:894:73: error: no member named 'require_same_orientation' in namespace 'CGAL::internal_np'
  const bool same_orientation = choose_param(get_param(np, internal_np::require_same_orientation), false);
```

## Source Code

https://github.com/CGAL/cgal/blob/releases/CGAL-4.14-branch/Polygon_mesh_processing/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): OSX 10.14
* Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4) 
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Could you please check that https://github.com/CGAL/cgal/pull/3882 fixes your pb? (I'm a bit surprised because we have a test checking documented headers are compilable...). It is does fix it, @maxGimeno could you please check if the test is still running in travis.

**Comment by domparise** [comment]
It would appear to me that including the missing directive from #3882 yields further compilation errors in the repair_polygon_soup_example:

## Compilation Errors

In file included from /Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:4:
In file included from /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:26:
/opt/local/include/CGAL/boost/graph/parameters_interface.h:22:26: error: unknown type name 'vertex_point_t'; did you mean 'CGAL::vertex_point_t'?
CGAL_add_named_parameter(vertex_point_t, vertex_point, vertex_point_map)
                         ^
/opt/local/include/CGAL/boost/graph/properties.h:106:14: note: 'CGAL::vertex_point_t' declared here
using boost::vertex_point_t;
             ^
In file included from /Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:4:
In file included from /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:26:
/opt/local/include/CGAL/boost/graph/parameters_interface.h:22:42: error: C++ requires a type specifier for all declarations
CGAL_add_named_parameter(vertex_point_t, vertex_point, vertex_point_map)
                                         ^
/opt/local/include/CGAL/boost/graph/parameters_interface.h:22:56: error: unknown type name 'vertex_point_map'; did you mean 'CGAL::vertex_point_t'?
CGAL_add_named_parameter(vertex_point_t, vertex_point, vertex_point_map)
                                                       ^
/opt/local/include/CGAL/boost/graph/properties.h:106:14: note: 'CGAL::vertex_point_t' declared here
using boost::vertex_point_t;
             ^
In file included from /Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:4:
In file included from /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:26:
/opt/local/include/CGAL/boost/graph/parameters_interface.h:23:1: error: expected function body after function declarator
CGAL_add_named_parameter(halfedge_index_t, halfedge_index, halfedge_index_map)
^
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:12:9: error: use of undeclared identifier 'K'
typedef K::Point_3                                              Point_3;
        ^
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:25:20: error: excess elements in scalar initializer
  points.push_back(Point_3(0,0,0));
                   ^        ~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:26:20: error: excess elements in scalar initializer
  points.push_back(Point_3(1,0,0));
                   ^        ~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:27:20: error: excess elements in scalar initializer
  points.push_back(Point_3(0,1,0));
                   ^        ~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:28:20: error: excess elements in scalar initializer
  points.push_back(Point_3(-1,0,0));
                   ^         ~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:29:20: error: excess elements in scalar initializer
  points.push_back(Point_3(0,-1,0));
                   ^        ~~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:30:20: error: excess elements in scalar initializer
  points.push_back(Point_3(0,1,0)); // duplicate point
                   ^        ~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:31:20: error: excess elements in scalar initializer
  points.push_back(Point_3(0,-2,0)); // unused point
                   ^        ~~~~~
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:70:8: error: no member named 'repair_polygon_soup' in namespace
      'CGAL::Polygon_mesh_processing'
  PMP::repair_polygon_soup(points, polygons);
  ~~~~~^
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:71:8: error: no member named 'orient_polygon_soup' in namespace
      'CGAL::Polygon_mesh_processing'
  PMP::orient_polygon_soup(points, polygons);
  ~~~~~^
/Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:74:8: error: no member named 'polygon_soup_to_polygon_mesh' in namespace
      'CGAL::Polygon_mesh_processing'
  PMP::polygon_soup_to_polygon_mesh(points, polygons, mesh);
  ~~~~~^
15 errors generated.
make[2]: *** [CMakeFiles/repair_polygon_soup_example.dir/repair_polygon_soup_example.cpp.o] Error 1
make[1]: *** [CMakeFiles/repair_polygon_soup_example.dir/all] Error 2
make: *** [all] Error 2

**Comment by sloriot** [comment]
wrong header sorry. I've updated the PR. Could you please try again? I've tried to compile the header alone without the patch and I did not have any compilation error. Might be specific to a boost version.

**Comment by domparise** [comment]
Using Boost 1.66.0. 

Seems like I'm getting the same error with the updated header. For my understanding, what is the proper protocol to recompile an update to a header in the main library? I believe I need to first reconfig the cmake and recompile the main library from the root directory, then move to the example directory and reconfig the cmake and recompile that, correct?

This is a good test of new users with no knowledge picking up the project. Fwiw the 1.13.1 branch all worked great and I could pick it up with no knowledge, we just happen to want these new feature that are in 1.14.

**Comment by sloriot** [comment]
This is very strange. Do you have only one version of CGAL installed?

**Comment by domparise** [comment]
I have two on my system, testing 4.13.1 alongside 4.14.0, both sitting on my desktop. I recompile and run “make install” when switching between versions. 

I may have messed up some config, but if I rebuild from the downloadable tar file and make the changes proposed I still get the same result.

**Comment by sloriot** [comment]
Could you give some details about how you proceed from scratch?

**Comment by lrineau** [comment]
Fixed by #3882.

**Comment by domparise** [comment]
Sorry for the delay, but this still not building on my system. 

By "proceed from scratch" I meant:
1) download the 4.14 tar from the [release page](https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.14).
2) paste "#include <CGAL/boost/graph/named_function_params.h>" onto line 26 of /include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
3) compile the top level directory 
4) compile the Polygon_mesh_processing example directory 

Doing so still yields the compiling error pasted in my above comment. Should I be downloading the source repository from a more recent branch for this fix to work?

**Comment by sloriot** [comment]
Here is what I tried using:
```
> uname -a
Darwin cezanne.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
> c++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

then in header-only and compiled mode I add no issue compiling ` repair_polygon_soup_example.cpp`:

```
wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.14/CGAL-4.14.tar.xz
tar xf CGAL-4.14.tar.xz 
cd CGAL-4.14
mkdir build
cd build &&  cmake -DCMAKE_BUILD_TYPE=Release .. &&  make -j4
cd ../examples/Polygon_mesh_processing/
mkdir build &&  cd build
CGAL_DIR=../../../build/ cmake -DCMAKE_BUILD_TYPE=Release ..
make repair_polygon_soup_example
cd ..
mkdir build_ho
cd build_ho/
CGAL_DIR=../../.. cmake -DCMAKE_BUILD_TYPE=Release ..
make repair_polygon_soup_example
```

The only thing I see is that you have CGAL header read from another location that the release.

**Comment by domparise** [comment]
```
>  uname -a
Darwin dom-pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
> c++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I believe followed your same procedure and still had an issue. 

```
 > make repair_polygon_soup_example
[ 50%] Building CXX object CMakeFiles/repair_polygon_soup_example.dir/repair_polygon_soup_example.cpp.o
In file included from /Users/dom/Desktop/CGAL-4.14/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp:4:
/usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:894:77: error: no member named 'erase_all_duplicates' in namespace 'CGAL::internal_np'
  const bool erase_all_duplicates = choose_param(get_param(np, internal_np::erase_all_duplicates), false);
                                                               ~~~~~~~~~~~~~^
/usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:895:73: error: no member named 'require_same_orientation' in namespace 'CGAL::internal_np'
  const bool same_orientation = choose_param(get_param(np, internal_np::require_same_orientation), false);
                                                           ~~~~~~~~~~~~~^
2 errors generated.
make[3]: *** [CMakeFiles/repair_polygon_soup_example.dir/repair_polygon_soup_example.cpp.o] Error 1
make[2]: *** [CMakeFiles/repair_polygon_soup_example.dir/all] Error 2
make[1]: *** [CMakeFiles/repair_polygon_soup_example.dir/rule] Error 2
make: *** [repair_polygon_soup_example] Error 2
```

Could the discrepancy in Darwin Kernel Version be an issue?

**Comment by sloriot** [comment]
If you open the file `CGAL/boost/graph/parameters_interface.h` you should see `CGAL_add_named_parameter(erase_all_duplicates_t, erase_all_duplicates, erase_all_duplicates)`
Can you try putting a `#error FOOBAR` in this file to make sure it is read?

**Comment by afabri** [comment]
@domparise ping
