### ISSUE TITLE
Improve edge_collapse API

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4485]
* When passing a constrained edge map to `edge_collapse()` the user has to manually provide a placement wrapped into `Constrained_placement`. It would be much more user friendly to do it automatically as soon as a constrained edge map as been provided (+ check if not already done since we want to keep backward compatibility). We should also deprecate the public definition of the class.

* Having also a `constrained_vertex_map` would also be interesting. Care has to be taken for the placement that will potentially have to handle both a vertex and a edge constrained map

* `Bounded_normal_placement` should be replaced by a named parameter, deprecate the class + handle backward compatibility

**Comment by lrineau** [comment]
@MaelRL @sloriot Maybe this issue is already fixed. There was a pull-request assigned to it, but it got cancelled. That was more than a year ago.

**Comment by MaelRL** [comment]
The pull request was doing some of the changes described in this issue, but also some other (not so good) stuff, which has not been extracted from the PR since then, so the issue is still valid
