### ISSUE TITLE
Tutorial runtime error

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#7120]
For example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-86/Classification_Examples/TestReport_Christo_MSVC-2019-Community-Release.gz)

**Comment by lrineau** [comment]
@SaillantNicolas The error code is `0xc0000135`. That is the error code for DLLs that are not found at runtime. It is probably the DLLs of Boost serialization and Boost iostream.

**Comment by lrineau** [comment]
> For example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-86/Classification_Examples/TestReport_Christo_MSVC-2019-Community-Release.gz)

As reported by Nicolas (IRL) the test results for CGAL-5.6-I-86 are two months old. That issue has been fixed since then. See for example [in CGAL-5.6-I-132 on the same platform](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-132/Classification_Examples/TestReport_Christo_MSVC-2019-Community-Release.gz).

**Comment by sloriot** [comment]
The error code that I actually meant to report is `Exit code 0xc0000409` like in CGAL-5.6-Ic-121, CGAL-5.6-Ic-126, CGAL-5.6-Ic-133, CGAL-5.6-Ic-134, ...

**Comment by sloriot** [comment]
Note that this is still an issue. See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-153/Classification_Examples/TestReport_Christo_MSVC-2022-Preview-Release.gz)

**Comment by sloriot** [comment]
@soesau @afabri maybe one of you could try to see if they can reproduce the error?

**Comment by afabri** [comment]
I just noticed that we have several executables that write to `std::ofstream out("classification.ply")`.   When run at the same time they may conflict. I will make a PR with different names.

**Comment by afabri** [comment]
> I just noticed that we have several executable that write to `std::ofstream out("classification.ply")`. When run at the same time they may conflict. I will make a PR with different names.

In fact the executable that has a problem has not the same file name :<

**Comment by afabri** [comment]
To seed default random also did not help to reproduce. Maybe it needs more trace output to narrow it down.

**Comment by soesau** [comment]
Same here, can't reproduce.

**Comment by afabri** [comment]
I noticed that the fairing step of the hole filling is not deterministic.

**Comment by afabri** [comment]
The crash happens when we [construct ](https://github.com/CGAL/cgal/blob/master/Classification/examples/Classification/gis_tutorial_example.cpp#L657)the constrained triangulation where we assume that there are no intersections, but there sometimes are.   So it seems that segments constructed [here](https://github.com/CGAL/cgal/blob/master/Classification/examples/Classification/gis_tutorial_example.cpp#L97) (with inexact constructions) intersect.

**Comment by sloriot** [comment]
If the input is a terrain, what about switching on the option `use_2d_constrained_delaunay_triangulation()` of hole filling?

**Comment by lrineau** [comment]
Fixed by the merge of https://github.com/CGAL/cgal/pull/7177, a month ago.
