### ISSUE TITLE
[MSVC] 

### ISSUE THREAD

**Issue by lbartoletti** [CGAL/cgal#7667]
_Please use the following template to help us solving your issue._

## Issue Details

Can't build specific code (Arrangement_on_surface_2) on MSVC 2017.

The specific line is:
        ring->addPoint(he->source()->point());

MSVC returns `'source' is not a member of 'CGAL::Arr_halfedge<V,H,F>'`

## Source Code

This code from SFCGAL can't build on MSVC: https://gitlab.com/Oslandia/SFCGAL/-/blob/master/src/algorithm/alphaShapes.cpp?ref_type=heads#L97-111

On UNIX-like compiler (gcc, clang, mingw) it's OK. 

h :
` CGAL::Iterator_transform<CGAL::Iterator_project<std::__1::__list_iterator<void*, void*>, CGAL::Cast_function_object<void*, CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck> >, CGAL::Arr_halfedge_base<CGAL::Segment_2<CGAL::Epeck> >, CGAL::Arr_face_base>*>, int, int, int, int>, CGAL      ::Arrangement_on_surface_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_default_dcel<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>> >>::_Halfedge_to_ccb_circulator>`

he:
```
CGAL::_HalfedgeDS_facet_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CG
      AL::Arr_default_dcel<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>> >>::Halfedge, CGAL::I_Filtered_iterator<CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck> >, CGAL::Arr_halfedge_base<CGAL::Segment_2<CGAL::Epeck> >, CGAL::Arr_face_base>, std::__1::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGA
      L::Point_2<CGAL::Epeck> >, CGAL::Arr_halfedge_base<CGAL::Segment_2<CGAL::Epeck> >, CGAL::Arr_face_base>> >, CGAL::Arrangement_on_surface_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_default_dcel<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL
      ::Epeck>> >>::_Is_valid_halfedge, CGAL::Arrangement_on_surface_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>, CGAL::Arr_default_dcel<CGAL::Arr_non_caching_segment_basic_traits_2<CGAL::Epeck>> >>::Halfedge, long, std::__1::bidirectional_iterator_tag>, CGAL:
      :Bidirectional_circulator_tag>

```

however on MSVC:
he:

`CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>, CGAL::Arr_halfedge_base<CGAL::Segment_2<CGAL::    Epeck>>, CGAL::Arr_face_base>`
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC 2017
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.6
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Loic (@lbartoletti): Your issue seems fixed in the branch `fix_build_cgal_56` of SFCGAL:
https://gitlab.com/Oslandia/SFCGAL/-/blob/fix_build_cgal_56/src/algorithm/alphaShapes.cpp?ref_type=heads#L97-111

Do you still consider this as a bug?

**Comment by lbartoletti** [comment]
> Loic (@lbartoletti): Your issue seems fixed in the branch `fix_build_cgal_56` of SFCGAL:
> https://gitlab.com/Oslandia/SFCGAL/-/blob/fix_build_cgal_56/src/algorithm/alphaShapes.cpp?ref_type=heads#L97-111

Hi Laurent,
Not at all, It's a WIP branch for tests, but this doesn't fix anything :)


> Do you still consider this as a bug?

Yes

**Comment by afabri** [comment]
@lrineau is that similar to the problem we plan to fix with #7410 ?

**Comment by lrineau** [comment]
> @lrineau is that similar to the problem we plan to fix with #7410 ?

It is probably similar in the sense that there are base classes involved, and implicit conversions. But here the issue is about handles/iterators in arrangement, and not ranges of those. I do not think `Prevent_deref` is involved.
