### ISSUE TITLE
Precompiled Polyhedron demo already contains the required DLLs

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#7721]
The zip file of the Polyhedron demo available in the Overview page already contains all the required DLLs. 
And more important: if one extracts `CGAL-demoDLLs.zip` into the folder and thus overwrites the DLLs that are already there, then the demo does not work anymore.

I don't know if it is the same for the other demos.

Note that [this page](https://doc.cgal.org/latest/Manual/windows.html#title15) should be fixed too.

**Comment by janetournois** [comment]
Hello @cjamin 
thanks for the report, we'll fix that

**Comment by lrineau** [comment]
I have modified the milestone. I think we should fix that in CGAL-5.6.1.

We need to remove all the lines
> **Common Demo Dlls:** [dlls](https://www.cgal.org/demo/5.6/CGAL-demoDLLs.zip)

from https://doc.cgal.org/latest/Manual/packages.html

**Comment by afabri** [comment]
It might make sense to load the html page in a text editor and remove "<b>Common Demo Dlls:</b> <a href="[https://www.cgal.org/demo/5.6/CGAL-demoDLLs.zip](view-source:https://www.cgal.org/demo/5.6/CGAL-demoDLLs.zip)">dlls</a><br>"

**Comment by sloriot** [comment]
It's done through a macro AFAIR

**Comment by janetournois** [comment]
> Note that [this page](https://doc.cgal.org/latest/Manual/windows.html#title15) should be fixed too.

I'm fixing that

**Comment by janetournois** [comment]
done

**Comment by afabri** [comment]
In case this is not fixed yet, one solution is to make the zip file for Common dlls empty, say with just a readme
