### ISSUE TITLE
Trying to use visitor in split() method

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8275]
_Please use the following template to help us solving your issue._

## Issue Details

I am using split function to intersect two surface meshes and I want to get the newly created points/edges during split so that I can remesh these points. From this [link](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html) I think I could use visitor to get what I want.  the surface meshes, named slope and slide respectively,  are shown as follows:

![image](https://github.com/CGAL/cgal/assets/9004748/a71e2c1b-b31e-46cb-8609-3244a4f7d228)
<img width="606" alt="企业微信截图_17180771721603" src="https://github.com/CGAL/cgal/assets/9004748/47a37b29-7efd-4e89-aabb-a88fc53d66af">

However, I could not get any infomation, `before_subface_creations, after_subface_created after_subface_creations` all the 3 call back functions do not get called. 

/

I hope if anyone could help me solve this. Thank you! 
## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/boost/graph/selection.h>
#include <CGAL/Polygon_mesh_processing/remesh.h>

#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Polygon_mesh_processing/clip.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

#include <iostream>
#include <string>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Exact_predicates_exact_constructions_kernel EK;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;
typedef boost::graph_traits<Mesh>::vertex_descriptor vertex_descriptor;
typedef Mesh::Property_map<vertex_descriptor, EK::Point_3> Exact_point_map;
typedef boost::graph_traits<Mesh>::face_descriptor            face_descriptor;
typedef boost::graph_traits<Mesh>::edge_descriptor            edge_descriptor;
typedef boost::graph_traits<Mesh>::halfedge_descriptor        halfedge_descriptor;


namespace PMP = CGAL::Polygon_mesh_processing;
namespace params = CGAL::parameters;

class Insert_iterator
{
    typedef std::unordered_map<face_descriptor, face_descriptor> Container;
    Container& container;
public:

    Insert_iterator(Container& c)
        : container(c) {}

    Insert_iterator&
        operator=(const std::pair<face_descriptor, face_descriptor>& p)
    {
        container[p.second] = p.first;
        return *this;
    }

    Insert_iterator&
        operator*() { return *this; }

    Insert_iterator
        operator++(int) { return *this; }

};
struct Visitor : public CGAL::Polygon_mesh_processing::Corefinement::Default_visitor<Mesh>
{
    typedef std::unordered_map<face_descriptor, face_descriptor> Container;

    Container& container;
    face_descriptor qfd;

    Visitor(Container& container)
        : container(container)
    {}

    void before_subface_creations(face_descriptor fd)
    {
        std::cout << "split : " << fd << " into:" << std::endl;
        Container::iterator it = container.find(fd);
        qfd = it->second;
        container.erase(it);
    }

    void after_subface_created(face_descriptor fd)
    {
        std::cout << "  " << fd;
        container[fd] = qfd;
    }

    void after_subface_creations()
    {
        std::cout << std::endl;
    }
};

int main(int argc, char* argv[])
{
    const std::string filename1 = (argc > 1) ? argv[1] : CGAL::data_file_path("meshes/slope.off");
    const std::string filename2 = (argc > 2) ? argv[2] : CGAL::data_file_path("meshes/slide.off");

    Mesh mesh1, mesh2;
    if (!PMP::IO::read_polygon_mesh(filename1, mesh1) || !PMP::IO::read_polygon_mesh(filename2, mesh2))
    {
        std::cerr << "Invalid input." << std::endl;
        return 1;
    }

    if (PMP::does_self_intersect(mesh1) || PMP::does_self_intersect(mesh2))
    {
        std::cerr << "self intersect input." << std::endl;
        return 1;
    }

    std::unordered_map<face_descriptor, face_descriptor> t2q;
    Visitor v(t2q);

    PMP::split(mesh1, mesh2, params::do_not_modify(true), params::visitor(v).do_not_modify(true));

    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11
* Compiler: MSVC
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:  5.6.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The visitor should be in the first named parameter, not the second one (you have to expand the doc to see the np_tm only). This kind of problem should be fixed when https://github.com/CGAL/cgal/pull/7966 is merged and used for all functions.

**Comment by citystrawman** [comment]
> The visitor should be in the first named parameter, not the second one (you have to expand the doc to see the np_tm only). This kind of problem should be fixed when #7966 is merged and used for all functions.

Thank you for your kind remind, but after changing the visitor to the first name parameter, the call backs are still not called, and the visitor v is still empty after running split method.

**Comment by sloriot** [comment]
You cannot put `do_not_modify(true)` for the first mesh. Then the signature of the visitor function are incorrect, the last argument is a mesh. `container.find(fd);` might return `container.end()` which will lead to segfault if you access the iterator. On CGAL side, you'll need #8276 to get it working after fixing the other issues.

**Comment by citystrawman** [comment]
> You cannot put `do_not_modify(true)` for the first mesh. Then the signature of the visitor functions are incorrect, the last argument is a mesh. `container.find(fd);` might return `container.end()` which will lead to segfault if you access the iterator. On CGAL side, you'll need #8276 to get it working after fixing the other issues.

Sorry I may not catch your words. 
You mean Split() method should be written like this: `PMP::split(mesh1, mesh2, params::visitor(v))`? (I tried this, and it still does not work.) 
Or do you mean that, the visitor is not working correctly until the issue is fixed?

**Comment by citystrawman** [comment]
> You cannot put `do_not_modify(true)` for the first mesh. Then the signature of the visitor functions are incorrect, the last argument is a mesh. `container.find(fd);` might return `container.end()` which will lead to segfault if you access the iterator. On CGAL side, you'll need #8276 to get it working after fixing the other issues.

Hi, after reading this [post](https://github.com/CGAL/cgal/issues/4638), I changed split to clip method, and now `before_subface_creations` get called. At first  `before_subface_creations` has code as follows:
```
void before_subface_creations(face_descriptor fd)
    {
        std::cout << "split : " << fd << " into:" << std::endl;
        Container::iterator it = container.find(fd);
        qfd = it->second;
        container.erase(it);
    }
```
which is copied from official code example. 
However when I run the code, a face_descriptor which has the same idx_(in my example, f1134) run into this callback twice. 
I am confused about it because I think face_descriptor should be unique and if a face_descriptor get called, the container will erase it, then why a face_descriptor that has the same idx_ run into the callback twice?

**Comment by sloriot** [comment]
Copy/pasted from [here](https://stackoverflow.com/questions/78611070/cgal-before-subface-creationsface-descriptor-f-old-mesh-callback-run-into-th) You are mixing things up. The example you are pointing out is for triangulating a mesh, and the visitor must model the concept [PMPTriangulateFaceVisitor](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPTriangulateFaceVisitor.html). If you are using corefinement, the visitor must model the concept [PMPCorefinementVisitor](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html). In clip (and corefinement) you have 2 meshes so the same id might appear twice but with different meshes.

**Comment by sloriot** [comment]
> Or do you mean that, the visitor is not working correctly until the issue is fixed?
Yes you need the aforementioned patch so that the visitor is correctly forwarded

**Comment by citystrawman** [comment]
> > Or do you mean that, the visitor is not working correctly until the issue is fixed?
> 
> Yes you need the aforementioned patch so that the visitor is correctly forwarded

Thank you, BTW I see that you just added ` .visitor(uv)` in clip.h line 941, If I want to use this new feature now, can I just use the 5.5.x branch and just add the same code ?

**Comment by citystrawman** [comment]
> Copy/paste of my answer [here](https://stackoverflow.com/questions/78611070/cgal-before-subface-creationsface-descriptor-f-old-mesh-callback-run-into-th): You are mixing things up. The example you are pointing out is for triangulating a mesh, and the visitor must model the concept [PMPTriangulateFaceVisitor](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPTriangulateFaceVisitor.html). If you are using corefinement, the visitor must model the concept [PMPCorefinementVisitor](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html). In clip (and corefinement) you have 2 meshes so the same id might appear twice but with different meshes.

OK. So params::visitor(v) actually deals with both the tm as well as clipper/splitter even though it is associated as np_tm?

**Comment by lrineau** [comment]
The PR #8275 is now merged.

**Comment by citystrawman** [comment]
> The PR #8275 is now merged.

Thanks. I just switched it to 5.5.x-branch, but its structure is different from the release version, and after configure it by cmake-gui, I only get the projects like this:
![image](https://github.com/CGAL/cgal/assets/9004748/1daf40c7-31cc-46a8-b1a0-289d6aba6715)

May I know how I can compile the polygon mesh processing package?  @sloriot @lrineau  Thank you

**Comment by sloriot** [comment]
If you are using cmake, it is just a matter of modifying your CGAL_DIR to point to the git checkout.

**Comment by citystrawman** [comment]
> If you are using cmake, it is just a matter of modifying your CGAL_DIR to point to the git checkout.

I just found the correct CMAkeList.txt for Polygon Mesh Processing Examples. But after running the code I got `CGAL_DATA_DIR=''"`, should I set CGAL_DATA_DIR?

**Comment by citystrawman** [comment]
> If you are using cmake, it is just a matter of modifying your CGAL_DIR to point to the git checkout.

OK. Thank you!

**Comment by citystrawman** [comment]
> If you are using cmake, it is just a matter of modifying your CGAL_DIR to point to the git checkout.

Hi, just have another question: I am trying to implement some halfedge callbacks such as `after_edge_copy ` `after_edge_duplicated ` `intersection_edge_copy `, etc. but all these callbacks are not get called when I use `clip `funtion. Is that  correct ?

**Comment by sloriot** [comment]
if the clip is done with `clip_volume=false` there is no edge copy/duplication
